/*----- PROTECTED REGION ID(PS_psp_405StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        PS_psp_405StateMachine.cpp
//
// description : State machine file for the PS_psp_405 class
//
// project :     GW_INSTEK PSP-405
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <PS_psp_405.h>

/*----- PROTECTED REGION END -----*/	//	PS_psp_405::PS_psp_405StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace PS_psp_405_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405::is_volt_meas_allowed()
 *	Description : Execution allowed for volt_meas attribute
 */
//--------------------------------------------------------
bool PS_psp_405::is_volt_meas_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for volt_meas attribute in read access.
	/*----- PROTECTED REGION ID(PS_psp_405::volt_measStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405::volt_measStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405::is_curr_meas_allowed()
 *	Description : Execution allowed for curr_meas attribute
 */
//--------------------------------------------------------
bool PS_psp_405::is_curr_meas_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for curr_meas attribute in read access.
	/*----- PROTECTED REGION ID(PS_psp_405::curr_measStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405::curr_measStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405::is_volt_level_allowed()
 *	Description : Execution allowed for volt_level attribute
 */
//--------------------------------------------------------
bool PS_psp_405::is_volt_level_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for volt_level attribute in read access.
	/*----- PROTECTED REGION ID(PS_psp_405::volt_levelStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405::volt_levelStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405::is_curr_level_allowed()
 *	Description : Execution allowed for curr_level attribute
 */
//--------------------------------------------------------
bool PS_psp_405::is_curr_level_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for curr_level attribute in read access.
	/*----- PROTECTED REGION ID(PS_psp_405::curr_levelStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405::curr_levelStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool PS_psp_405::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(PS_psp_405::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool PS_psp_405::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(PS_psp_405::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405::OffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405::is_UdpateAllTheStatusValues_allowed()
 *	Description : Execution allowed for UdpateAllTheStatusValues attribute
 */
//--------------------------------------------------------
bool PS_psp_405::is_UdpateAllTheStatusValues_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for UdpateAllTheStatusValues command.
	/*----- PROTECTED REGION ID(PS_psp_405::UdpateAllTheStatusValuesStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405::UdpateAllTheStatusValuesStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(PS_psp_405::PS_psp_405StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PS_psp_405::PS_psp_405StateAllowed.AdditionalMethods

}	//	End of namespace
