/*----- PROTECTED REGION ID(PS_psp_405Class.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        PS_psp_405Class.cpp
//
// description : C++ source for the PS_psp_405Class.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the PS_psp_405 once per process.
//
// project :     GW_INSTEK PSP-405
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <PS_psp_405Class.h>

/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class.cpp

//-------------------------------------------------------------------
/**
 *	Create PS_psp_405Class singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_PS_psp_405_class(const char *name) {
		return PS_psp_405_ns::PS_psp_405Class::init(name);
	}
}

namespace PS_psp_405_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
PS_psp_405Class *PS_psp_405Class::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		PS_psp_405Class::PS_psp_405Class(string &s)
 * description : 	constructor for the PS_psp_405Class
 *
 * @param s	The class name
 */
//--------------------------------------------------------
PS_psp_405Class::PS_psp_405Class(string &s):PowerSuppliesAbst_ns::PowerSuppliesAbstClass(s)
{
	cout2 << "Entering PS_psp_405Class constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(PS_psp_405Class::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::constructor

	cout2 << "Leaving PS_psp_405Class constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		PS_psp_405Class::~PS_psp_405Class()
 * description : 	destructor for the PS_psp_405Class
 */
//--------------------------------------------------------
PS_psp_405Class::~PS_psp_405Class()
{
	/*----- PROTECTED REGION ID(PS_psp_405Class::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		PS_psp_405Class::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
PS_psp_405Class *PS_psp_405Class::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new PS_psp_405Class(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		PS_psp_405Class::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
PS_psp_405Class *PS_psp_405Class::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		OnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OnClass::execute(): arrived" << endl;
	((static_cast<PS_psp_405 *>(device))->on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		OffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OffClass::execute(): arrived" << endl;
	((static_cast<PS_psp_405 *>(device))->off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		UpdateAllTheStatusValuesClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *UpdateAllTheStatusValuesClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "UpdateAllTheStatusValuesClass::execute(): arrived" << endl;
	((static_cast<PS_psp_405 *>(device))->update_all_the_status_values());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetVoltageLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetVoltageLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetVoltageLevelClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PS_psp_405 *>(device))->set_voltage_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetCurrentLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetCurrentLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetCurrentLevelClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PS_psp_405 *>(device))->set_current_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetMaximumVoltageLimitClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetMaximumVoltageLimitClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetMaximumVoltageLimitClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PS_psp_405 *>(device))->set_maximum_voltage_limit(argin));
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum PS_psp_405Class::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum PS_psp_405Class::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum PS_psp_405Class::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void PS_psp_405Class::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "Socket";
	prop_desc = "Socket Tango device name in format ``domain/family/member``";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void PS_psp_405Class::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("GW_INSTEK PSP-405");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Device Server for power supply ``GW_INSTEK PSP-405``");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("PS_psp_405");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void PS_psp_405Class::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(PS_psp_405Class::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new PS_psp_405(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		PS_psp_405 *dev = static_cast<PS_psp_405 *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(PS_psp_405Class::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void PS_psp_405Class::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(PS_psp_405Class::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::attribute_factory_before
	//	Call atribute_factory for inherited class
	PowerSuppliesAbst_ns::PowerSuppliesAbstClass::attribute_factory(att_list);

	//	Attribute : volt_meas - Check if not concrete in inherited class
	Tango::Attr *volt_measAttr = get_attr_object_by_name(att_list, "volt_meas");
	if (volt_measAttr == NULL)
	{
		//	Attribute : volt_meas
		volt_measAttrib	*volt_meas = new volt_measAttrib();
		Tango::UserDefaultAttrProp	volt_meas_prop;
		//	description	not set for volt_meas
		//	label	not set for volt_meas
		//	unit	not set for volt_meas
		//	standard_unit	not set for volt_meas
		//	display_unit	not set for volt_meas
		//	format	not set for volt_meas
		//	max_value	not set for volt_meas
		//	min_value	not set for volt_meas
		//	max_alarm	not set for volt_meas
		//	min_alarm	not set for volt_meas
		//	max_warning	not set for volt_meas
		//	min_warning	not set for volt_meas
		//	delta_t	not set for volt_meas
		//	delta_val	not set for volt_meas
		
		volt_meas->set_default_properties(volt_meas_prop);
		//	Not Polled
		volt_meas->set_disp_level(Tango::OPERATOR);
		//	Not Memorized
		att_list.push_back(volt_meas);
	}

	//	Attribute : curr_meas - Check if not concrete in inherited class
	Tango::Attr *curr_measAttr = get_attr_object_by_name(att_list, "curr_meas");
	if (curr_measAttr == NULL)
	{
		//	Attribute : curr_meas
		curr_measAttrib	*curr_meas = new curr_measAttrib();
		Tango::UserDefaultAttrProp	curr_meas_prop;
		//	description	not set for curr_meas
		//	label	not set for curr_meas
		//	unit	not set for curr_meas
		//	standard_unit	not set for curr_meas
		//	display_unit	not set for curr_meas
		//	format	not set for curr_meas
		//	max_value	not set for curr_meas
		//	min_value	not set for curr_meas
		//	max_alarm	not set for curr_meas
		//	min_alarm	not set for curr_meas
		//	max_warning	not set for curr_meas
		//	min_warning	not set for curr_meas
		//	delta_t	not set for curr_meas
		//	delta_val	not set for curr_meas
		
		curr_meas->set_default_properties(curr_meas_prop);
		//	Not Polled
		curr_meas->set_disp_level(Tango::OPERATOR);
		//	Not Memorized
		att_list.push_back(curr_meas);
	}

	//	Attribute : volt_level - Check if not concrete in inherited class
	Tango::Attr *volt_levelAttr = get_attr_object_by_name(att_list, "volt_level");
	if (volt_levelAttr == NULL)
	{
		//	Attribute : volt_level
		volt_levelAttrib	*volt_level = new volt_levelAttrib();
		Tango::UserDefaultAttrProp	volt_level_prop;
		//	description	not set for volt_level
		//	label	not set for volt_level
		//	unit	not set for volt_level
		//	standard_unit	not set for volt_level
		//	display_unit	not set for volt_level
		//	format	not set for volt_level
		//	max_value	not set for volt_level
		//	min_value	not set for volt_level
		//	max_alarm	not set for volt_level
		//	min_alarm	not set for volt_level
		//	max_warning	not set for volt_level
		//	min_warning	not set for volt_level
		//	delta_t	not set for volt_level
		//	delta_val	not set for volt_level
		
		volt_level->set_default_properties(volt_level_prop);
		//	Not Polled
		volt_level->set_disp_level(Tango::OPERATOR);
		//	Not Memorized
		att_list.push_back(volt_level);
	}

	//	Attribute : curr_level - Check if not concrete in inherited class
	Tango::Attr *curr_levelAttr = get_attr_object_by_name(att_list, "curr_level");
	if (curr_levelAttr == NULL)
	{
		//	Attribute : curr_level
		curr_levelAttrib	*curr_level = new curr_levelAttrib();
		Tango::UserDefaultAttrProp	curr_level_prop;
		//	description	not set for curr_level
		//	label	not set for curr_level
		//	unit	not set for curr_level
		//	standard_unit	not set for curr_level
		//	display_unit	not set for curr_level
		//	format	not set for curr_level
		//	max_value	not set for curr_level
		//	min_value	not set for curr_level
		//	max_alarm	not set for curr_level
		//	min_alarm	not set for curr_level
		//	max_warning	not set for curr_level
		//	min_warning	not set for curr_level
		//	delta_t	not set for curr_level
		//	delta_val	not set for curr_level
		
		curr_level->set_default_properties(curr_level_prop);
		//	Not Polled
		curr_level->set_disp_level(Tango::OPERATOR);
		//	Not Memorized
		att_list.push_back(curr_level);
	}

	//	Attribute : maximum_volt_limit
	maximum_volt_limitAttrib	*maximum_volt_limit = new maximum_volt_limitAttrib();
	Tango::UserDefaultAttrProp	maximum_volt_limit_prop;
	//	description	not set for maximum_volt_limit
	//	label	not set for maximum_volt_limit
	//	unit	not set for maximum_volt_limit
	//	standard_unit	not set for maximum_volt_limit
	//	display_unit	not set for maximum_volt_limit
	//	format	not set for maximum_volt_limit
	//	max_value	not set for maximum_volt_limit
	//	min_value	not set for maximum_volt_limit
	//	max_alarm	not set for maximum_volt_limit
	//	min_alarm	not set for maximum_volt_limit
	//	max_warning	not set for maximum_volt_limit
	//	min_warning	not set for maximum_volt_limit
	//	delta_t	not set for maximum_volt_limit
	//	delta_val	not set for maximum_volt_limit
	
	maximum_volt_limit->set_default_properties(maximum_volt_limit_prop);
	//	Not Polled
	maximum_volt_limit->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(maximum_volt_limit);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(PS_psp_405Class::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void PS_psp_405Class::pipe_factory()
{
	/*----- PROTECTED REGION ID(PS_psp_405Class::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::pipe_factory_before
	/*----- PROTECTED REGION ID(PS_psp_405Class::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void PS_psp_405Class::command_factory()
{
	/*----- PROTECTED REGION ID(PS_psp_405Class::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::command_factory_before
	//	Call command_factory for inherited class
	PowerSuppliesAbst_ns::PowerSuppliesAbstClass::command_factory();



	//	Get inherited Command object On if already created
	try
	{
		get_cmd_by_name("On");
	}
	catch (Tango::DevFailed &e)
	{
		//	Create On command object
		OnClass	*pOnCmd =
			new OnClass("On",
				Tango::DEV_VOID, Tango::DEV_VOID,
				"",
				"",
				Tango::OPERATOR);
		command_list.push_back(pOnCmd);
	}

	//	Get inherited Command object Off if already created
	try
	{
		get_cmd_by_name("Off");
	}
	catch (Tango::DevFailed &e)
	{
		//	Create Off command object
		OffClass	*pOffCmd =
			new OffClass("Off",
				Tango::DEV_VOID, Tango::DEV_VOID,
				"",
				"",
				Tango::OPERATOR);
		command_list.push_back(pOffCmd);
	}

	//	Get inherited Command object UpdateAllTheStatusValues if already created
	try
	{
		get_cmd_by_name("UpdateAllTheStatusValues");
	}
	catch (Tango::DevFailed &e)
	{
		//	Create UpdateAllTheStatusValues command object
		UpdateAllTheStatusValuesClass	*pUpdateAllTheStatusValuesCmd =
			new UpdateAllTheStatusValuesClass("UpdateAllTheStatusValues",
				Tango::DEV_VOID, Tango::DEV_VOID,
				"",
				"",
				Tango::OPERATOR);
		command_list.push_back(pUpdateAllTheStatusValuesCmd);
	}

	//	Get inherited Command object SetVoltageLevel if already created
	try
	{
		get_cmd_by_name("SetVoltageLevel");
	}
	catch (Tango::DevFailed &e)
	{
		//	Create SetVoltageLevel command object
		SetVoltageLevelClass	*pSetVoltageLevelCmd =
			new SetVoltageLevelClass("SetVoltageLevel",
				Tango::DEV_DOUBLE, Tango::DEV_VOID,
				"Voltage level",
				"",
				Tango::OPERATOR);
		command_list.push_back(pSetVoltageLevelCmd);
	}

	//	Get inherited Command object SetCurrentLevel if already created
	try
	{
		get_cmd_by_name("SetCurrentLevel");
	}
	catch (Tango::DevFailed &e)
	{
		//	Create SetCurrentLevel command object
		SetCurrentLevelClass	*pSetCurrentLevelCmd =
			new SetCurrentLevelClass("SetCurrentLevel",
				Tango::DEV_DOUBLE, Tango::DEV_VOID,
				"The current level",
				"",
				Tango::OPERATOR);
		command_list.push_back(pSetCurrentLevelCmd);
	}

	//	Command SetMaximumVoltageLimit
	SetMaximumVoltageLimitClass	*pSetMaximumVoltageLimitCmd =
		new SetMaximumVoltageLimitClass("SetMaximumVoltageLimit",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"The voltage limit max = 40.0V",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetMaximumVoltageLimitCmd);

	/*----- PROTECTED REGION ID(PS_psp_405Class::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		PS_psp_405Class::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void PS_psp_405Class::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(PS_psp_405Class::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		PS_psp_405Class::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void PS_psp_405Class::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		PS_psp_405 *dev = static_cast<PS_psp_405 *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(PS_psp_405Class::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : PS_psp_405Class::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *PS_psp_405Class::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(PS_psp_405Class::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	PS_psp_405Class::Additional Methods
} //	namespace
